spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #search-locations: "classpath:/config"
        #search-locations: "file:////C//chung//Documents//config_microservice//config"
        #search-locations: "file:////Users//chung//Documents//config_microservice//config"
        git:
          uri: "https://github.com/tranthanhchung-99/config-server-micro.git" # link to git
          default-label: main # git branch
          timeout: 5 # time for request to git if expired return exception
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "privateKeyOfTranThanhChung99"

server:
  port: 8071
