services:
  accounts:
    image: "tranthanhchung99/accounts:s4"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - "ttcms"
  loans:
    image: "tranthanhchung99/loans:s4"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - "ttcms"
  cards:
    image: "tranthanhchung99/cards:s4"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - "ttcms"

networks:
  ttcms:
    driver: "bridge"